project:
  type: book
  output-dir: _site
  resources:
    - assets/monodomain_amr.gif

engines: ['julia']
julia:
  project: "."

book:
  title: "MatrixFreeOperators.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    logo: https://github.com/user-attachments/assets/f7216152-0d6e-4459-8e65-b9ed59421638
    logo-href: https://rallypoint1.com
    right:
      - icon: star
        href: https://github.com/RallypointOne/MatrixFreeOperators.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/MatrixFreeOperators.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - pages/amr.qmd
        - pages/multigrid.qmd
        - pages/distributed.qmd
    - part: "API"
      chapters:
        - pages/api.qmd
    - part: "Resources"
      chapters:
        - pages/coverage.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: assets/styles.css
    number-sections: false
    theme:
      - flatly
      - assets/theme.scss
    include-after-body:
      - file: assets/_version-selector.html
